[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build]
include = ["grove/*"]

[project]
name = 'grove'
authors = [
    {name = "Kamen Hristov", email = "kamen.hristov.98@gmail.com"},
]
readme = "README.md"
requires-python = ">=3.10.2"
version = '0.0.1'
dependencies = [
    "aislab == 0.0.16",
    "asttokens == 2.2.1",
    "backcall == 0.2.0",
    "black == 23.3.0",
    "click == 8.1.3",
    "decorator == 5.1.1",
    "executing == 1.2.0",
    "ipython == 8.13.2",
    "jedi == 0.18.2",
    "joblib == 1.2.0",
    "matplotlib-inline == 0.1.6",
    "mypy-extensions == 1.0.0",
    "numpy == 1.24.3",
    "packaging == 23.1",
    "pandas == 2.0.1",
    "parso == 0.8.3",
    "pathspec == 0.11.1",
    "pexpect == 4.8.0",
    "pickleshare == 0.7.5",
    "platformdirs == 3.5.1",
    "prompt-toolkit == 3.0.38",
    "ptyprocess == 0.7.0",
    "pure-eval == 0.2.2",
    "Pygments == 2.15.1",
    "python-dateutil == 2.8.2",
    "pytz == 2023.3",
    "scikit-learn == 1.2.2",
    "scipy == 1.10.1",
    "six == 1.16.0",
    "stack-data == 0.6.2",
    "threadpoolctl == 3.1.0",
    "tomli == 2.0.1",
    "traitlets == 5.9.0",
    "tzdata == 2023.3",
    "wcwidth == 0.2.6",
]